#!/bin/bash

# Set select prompt
PS3='Enter your choice (q to quit): '

# QEMU Launch Options
DIR=/home/nanibot/kvm/disk
CPU=2
MEM=4G

if ! [[ -d $DIR ]]
then
	echo "Specified directory does not exist"
	echo "Please set \$DIR in the script"
	exit 1
fi

while read TAP
do
	TAP_STATUS=$(ip link show $TAP | sed -n 1p | awk -F ' ' '{print $11}')
	if [[ $TAP_STATUS == "DOWN" ]]
	then
		echo "Starting VM on $TAP"
		IFACE=$TAP
		break
	fi
done < <(ip tuntap | grep tap | awk -F ':' '{print $1}')

if [[ -z $IFACE ]]
then
	echo "No TAP interface available"
	exit 1
fi

DISK_COUNT=0
while read disk
do
	((DISK_COUNT++))
	disk_array[DISK_COUNT]=$disk
done < <(find $DIR -maxdepth 1 -name "*.qcow2" | sort)

if [[ $DISK_COUNT -eq 0 ]]
then
	echo "No disk images available to boot from"
	exit 1
fi

echo "Available disks"
echo "---------------"
select choice in "${disk_array[@]}"
do
	if [[ $REPLY == q ]]
	then
		echo "Quitting"
		exit

	elif ! [[ $REPLY  =~ ^[0-9]+$ ]]
	then
		echo "Invalid choice"
		echo "Try again"

	elif [[ $REPLY -le $DISK_COUNT && $REPLY -gt 0 ]]
	then
		# Generate placeholders for the to-be-generated MAC address
		vmac_ph1=$(shuf -i 10-99 -n 1)
		vmac_ph2=$(shuf -i 10-99 -n 1)
		VMAC=14:1f:ba:$vmac_ph1:$vmac_ph2:e8
		# Generate placeholders for to-be-generated SMBIOS UUID
		uuid_ph1=$(shuf -i 1000-9999 -n 1)
		uuid_ph2=$(shuf -i 1000-9999 -n 1)
		uuid="99999999-$uuid_ph1-$uuid_ph2-9999-999999999999"
		echo "Assigned $VMAC to the VM"
		echo "UUID=$uuid"
		# Call kvm
		kvm -m $MEM -smp $CPU -drive file=${disk_array[REPLY]},format=qcow2,if=virtio -vga qxl \
		-nic tap,mac=$VMAC,ifname=$IFACE,script=no,downscript=no,model=virtio \
		-smbios type=1,manufacturer=qemu,product=vm,version=1,serial=qemu,uuid=$uuid,sku=qemu,family=qemu \
		"$@" & &>/dev/null
		exit 0
	else
		echo "Invalid choice"
		echo "Try again"
	fi
done